Repository nixys/nxs-backup, pull requests merged in 2024-07, with the labels that each got.

#68 Update files+psql.values.yml include_jobs_configs
  docs/example/kubernetes/files+psql.values.yml
Labels: documentation

#66 feat(#26): Add CPU limit by count
  ctx/conf.go
  ctx/context.go
  misc/generals.go
  modules/backend/targz/targz.go
  modules/backup/psql_basebackup/psql_basebackup.go
Labels: enhancement

#72 fix: Delivery backups logic
  interfaces/storage.go
  modules/storage/ftp/ftp.go
Labels: bug

#74 fix: Add update FPT connection for subcommands
  modules/storage/ftp/ftp.go
Labels: bug

#75 feat(#57): Add compression option
  ctx/conf.go
  ctx/jobs_init.go
  modules/backup/external/external.go
  modules/backup/redis/redis.go
Labels: enhancement

#73 feat: Add backup list functionality
  .github/release.yml
  ctx/args.go
  ctx/context.go
  go.mod
  go.sum
  interfaces/job.go
  interfaces/storage.go
  misc/errors.go
  modules/backend/webdav/webdav.go
  modules/backup/desc_files/desc_files.go
  modules/backup/external/external.go
  modules/backup/inc_files/inc_files.go
  modules/backup/mongodump/mongodump.go
  modules/backup/mysql/mysql.go
  modules/backup/mysql_xtrabackup/mysql_xtrabackup.go
  modules/backup/psql/psql.go
  modules/backup/psql_basebackup/psql_basebackup.go
  modules/backup/redis/redis.go
  modules/cmd_handler/list_backups/list_backups.go
  modules/storage/ftp/ftp.go
  modules/storage/local/local.go
  modules/storage/nfs/nfs_v3.go
  modules/storage/s3/s3.go
  modules/storage/sftp/sftp.go
  modules/storage/smb/smb.go
  modules/storage/webdav/webdav.go
Labels: enhancement
